name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make blinker@relax
      run: make project product_name=blinker board_name=relax
    - name: make ankle@ankle
      run: make project product_name=ankle board_name=ankle
    - name: make unit tests
      run: make unit

