name: C/C++ CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
          release: '10.3-2021.10'
          path-env-var: ARM_GCC_BIN_FOLDER
          
    - name: build fallsafe on relax board
      run: ./build.sh XMC4800_F144x2048 fallsafe relax
    - name: build fallsafe on ankle board
      run: ./build.sh XMC4800_F144x2048 fallsafe ankle
      
    - name: build blinker on relax board
      run: ./build.sh XMC4800_F144x2048 blinker relax
    - name: build blinker on ankle board
      run: ./build.sh XMC4800_F144x2048 blinker ankle
 
    - name: build ankle on relax board
      run: ./build.sh XMC4800_F144x2048 ankle relax
    - name: build ankle on ankle board
      run: ./build.sh XMC4800_F144x2048 ankle ankle

    - name: build unit-tests
      run: ./build.sh unit

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: build unit-tests
      run: ./build.sh unit && ./run_test.sh 
    
