#ifndef ANKLE_PIN_MAPPING_H_
#define ANKLE_PIN_MAPPING_H_

#include "xmc_gpio.h"
#include "stdint.h"

namespace board
{

	typedef enum
	{
		SPI0_CH1_MOSI,
		SPI0_CH1_MISO,
		SPI0_CH1_CLK,
		SPI0_CH1_CS1,
		SPI1_CH0_MOSI,
		SPI1_CH0_MISO,
		SPI1_CH0_CLK,
		SPI1_CH0_CS1
	} pin_identifier;

	typedef struct
	{
		pin_identifier pin_id;
		XMC_GPIO_PORT_t *port;
		uint8_t pin;
		XMC_GPIO_MODE_t mode;
	} pin_conf_t;

	static pin_conf_t pin_mapping[] =
		{
			{SPI0_CH1_MOSI, XMC_GPIO_PORT2, 5, XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT2},
			{SPI0_CH1_MISO, XMC_GPIO_PORT2, 2, XMC_GPIO_MODE_INPUT_TRISTATE},
			{SPI0_CH1_CLK, XMC_GPIO_PORT2, 4, XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT2},
			{SPI0_CH1_CS1, XMC_GPIO_PORT2, 3, XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT2},
			{SPI1_CH0_MOSI, XMC_GPIO_PORT0, 5, XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT2},
			{SPI1_CH0_MISO, XMC_GPIO_PORT0, 4, XMC_GPIO_MODE_INPUT_TRISTATE},
			{SPI1_CH0_CLK, XMC_GPIO_PORT4, 0, XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT4},
			{SPI1_CH0_CS1, XMC_GPIO_PORT0, 6, XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT2}};
}

#endif
